### ISSUE TITLE
Pretrained models?

### ISSUE THREAD

**Issue by harkiratbehl** [facebookresearch/mmbt#5]
Hi,

Can you please provide pretrained models for the different models/baselines used in the paper?

**Comment by douwekiela** [comment]
Hi, mmbt is not a pretraining architecture - the underlying pretrained models are eg just BERT and ResNet. If you're asking for the models finetuned on the individual tasks, we don't have those lying around anymore unfortunately. It should be relatively straightforward to train these though with the scripts in this repository (or check out the much better MMF codebase - https://github.com/facebookresearch/mmf) since the datasets are not super huge.

**Comment by harkiratbehl** [comment]
Training with this codebase was quite easy, thanks. I wouldn't really call MMF a better codebase, because it is not at all easy to modify.
